### ISSUE TITLE
Handle TTL or some way of delete file

### ISSUE THREAD

**Issue by magnetik** [solusipse/fiche#7]
Well almost everything is in the title, I would like to have a way to delete existing file.

**Comment by solusipse** [comment]
Maybe it's worth to consider to allow user delete his paste in the first 24 hours after posting it, if request comes from the same ip. I think that there's no other reasonable way to implement this while using netcat. And since I want to keep things simple, I'm not planning to move to other solutions. I'll think about this, thank you! Im closing that now, will reopen when I'll decide to do that. By the way, on http://termbin.com pastes are now deleted automatically when they're older that one month.
